package com.bobocode.utility;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.SQLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class CustomJdbcTemplateTest {

    private CustomJdbcTemplate db;

    @BeforeEach
    void setUp() throws SQLException {
        String h2Url = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1";

        com.zaxxer.hikari.HikariConfig config = new com.zaxxer.hikari.HikariConfig();
        config.setJdbcUrl(h2Url);
        config.setUsername("sa");
        config.setPassword("");
        javax.sql.DataSource dataSource = new com.zaxxer.hikari.HikariDataSource(config);

        db = new CustomJdbcTemplate(dataSource);

        db.execute("DROP TABLE IF EXISTS roles");
        db.execute("CREATE TABLE roles (role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50))");
    }

    @Test
    void testExecuteAndFindOne() {
        // Given
        db.execute("INSERT INTO roles (name) VALUES (?)", "ADMIN");

        // When
        String roleName = db.findOne(
                "SELECT name FROM roles WHERE name = ?",
                rs -> {
                    try {
                        return rs.getString("name");
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                },
                "ADMIN"
        );

        // Then
        assertNotNull(roleName);
        assertEquals("ADMIN", roleName);
    }

    @Test
    void testFindMany() {
        // Given
        db.execute("INSERT INTO roles (name) VALUES (?)", "USER");
        db.execute("INSERT INTO roles (name) VALUES (?)", "MODERATOR");

        // When
        List<String> roles = db.findMany(
                "SELECT name FROM roles",
                rs -> {
                    try {
                        return rs.getString("name");
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                }
        );

        // Then
        assertEquals(2, roles.size());
        assertTrue(roles.contains("USER"));
        assertTrue(roles.contains("MODERATOR"));
    }
}