CREATE TABLE IF NOT EXISTS roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) UNIQUE NOT NULL,
    password  VARCHAR(255)        NOT NULL,
    lastname  VARCHAR(100)        NOT NULL,
    firstname VARCHAR(100)        NOT NULL,
    age       INT,
    gender    VARCHAR(20),
    role_id   BIGINT              NOT NULL REFERENCES roles (role_id),
    is_active BOOLEAN             DEFAULT true
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS products
(
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    price       NUMERIC(19, 2) NOT NULL,
    category_id BIGINT         NOT NULL REFERENCES categories (category_id),
    is_active   BOOLEAN        DEFAULT true
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL REFERENCES users (user_id),
    purchase_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items
(
    order_item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT         NOT NULL REFERENCES orders (order_id),
    product_id        BIGINT         NOT NULL REFERENCES products (product_id),
    price_at_purchase NUMERIC(19, 2) NOT NULL,
    quantity          INT            NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS bucket
(
    bucket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT UNIQUE NOT NULL REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS bucket_items
(
    bucket_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_id      BIGINT NOT NULL REFERENCES bucket (bucket_id),
    product_id     BIGINT NOT NULL REFERENCES products (product_id) ON DELETE CASCADE,
    quantity       INT    NOT NULL,

    CONSTRAINT uq_bucket_product
        UNIQUE (bucket_id, product_id)
);

