spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/applicationDB?options=-c+timezone=Europe/Kyiv}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000