spring.profiles.active=local

app.features=auth-shop-cart-admin

app.datetime.launch-date=2026-12-31
app.datetime.launch-time=15:30:00
app.datetime.launch-timestamp=2026-12-31T15:30:00
app.datetime.session-timeout=30m
