package com.bobocode.services.system;

import com.bobocode.utility.CustomJdbcTemplate;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

import static org.assertj.core.api.Assertions.assertThat;

class SystemInitializerTest {

    private CustomJdbcTemplate customJdbcTemplate;
    private SystemInitializer systemInitializer;
    private DriverManagerDataSource dataSource;

    @BeforeEach
    void setUp() {
        dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
        dataSource.setUsername("sa");
        dataSource.setPassword("");

        customJdbcTemplate = new CustomJdbcTemplate(dataSource);
        systemInitializer = new SystemInitializer(customJdbcTemplate);

        JdbcTemplate springJdbcTemplate = new JdbcTemplate(dataSource);

        springJdbcTemplate.execute("DROP TABLE IF EXISTS bucket CASCADE");
        springJdbcTemplate.execute("DROP TABLE IF EXISTS users CASCADE");
        springJdbcTemplate.execute("DROP TABLE IF EXISTS roles CASCADE");

        springJdbcTemplate.execute("CREATE TABLE roles ("
                + "role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "name VARCHAR(50) NOT NULL UNIQUE)");

        springJdbcTemplate.execute("CREATE TABLE users ("
                + "user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "email VARCHAR(255), "
                + "password VARCHAR(255), "
                + "lastname VARCHAR(255), "
                + "firstname VARCHAR(255), "
                + "age INT, "
                + "gender VARCHAR(20), "
                + "role_id INT, "
                + "is_active BOOLEAN DEFAULT TRUE)");

        springJdbcTemplate.execute("CREATE TABLE bucket ("
                + "bucket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "user_id INT)");

        springJdbcTemplate.execute("MERGE INTO roles (name) KEY(name) VALUES ('USER')");
    }

    @AfterEach
    void tearDown() {
        JdbcTemplate springJdbcTemplate = new JdbcTemplate(dataSource);
        springJdbcTemplate.execute("SET REFERENTIAL_INTEGRITY FALSE");
        springJdbcTemplate.execute("DROP TABLE IF EXISTS bucket");
        springJdbcTemplate.execute("DROP TABLE IF EXISTS users");
        springJdbcTemplate.execute("DROP TABLE IF EXISTS roles");
        springJdbcTemplate.execute("SET REFERENTIAL_INTEGRITY TRUE");
    }

    @Test
    @DisplayName("Should skip setup if admin already exists in database")
    void shouldSkipSetupWhenAdminExists() {
        JdbcTemplate springJdbcTemplate = new JdbcTemplate(dataSource);
        springJdbcTemplate.update(
                "INSERT INTO users (email, password, lastname, firstname, role_id) VALUES (?, ?, ?, ?, ?)",
                "admin@grid.com", "pass123", "Doe", "John", 1
        );

        Scanner scanner = new Scanner(System.in);
        systemInitializer.initializeSystem(scanner);

        Integer count = springJdbcTemplate.queryForObject("SELECT COUNT(*) FROM users", Integer.class);
        assertThat(count).isEqualTo(1);
    }

    @Test
    @DisplayName("Should create first admin when database is empty")
    void shouldCreateFirstAdminWhenEmpty() {
        String simulatedConsoleInput = "Alex\nStoianov\nalex@grid.com\nStrongPassword123!\n";
        provideInput(simulatedConsoleInput);

        try (Scanner scanner = new Scanner(System.in, StandardCharsets.UTF_8)) {
            systemInitializer.initializeSystem(scanner);
        }

        JdbcTemplate springJdbcTemplate = new JdbcTemplate(dataSource);
        Integer count = springJdbcTemplate.queryForObject("SELECT COUNT(*) FROM users WHERE role_id = 1", Integer.class);
        assertThat(count).isEqualTo(1);

        String email = springJdbcTemplate.queryForObject("SELECT email FROM users WHERE role_id = 1", String.class);
        assertThat(email).isEqualTo("alex@grid.com");
    }

    private void provideInput(String data) {
        InputStream testInput = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8));
        System.setIn(testInput);
    }
}