CREATE TABLE IF NOT EXISTS roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) UNIQUE NOT NULL,
    password  VARCHAR(255)        NOT NULL,
    lastname  VARCHAR(100)        NOT NULL,
    firstname VARCHAR(100)        NOT NULL,
    age       INT,
    gender    VARCHAR(20),
    role_id   BIGINT              NOT NULL REFERENCES roles (role_id),
    is_active BOOLEAN             DEFAULT true
);
