CREATE TABLE IF NOT EXISTS orders
(
    order_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL,
    purchase_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items
(
    order_item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT         NOT NULL REFERENCES orders (order_id),
    product_id        BIGINT         NOT NULL,
    product_name      VARCHAR(255),
    price_at_purchase NUMERIC(19, 2) NOT NULL,
    quantity          INT            NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS bucket
(
    bucket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS bucket_items
(
    bucket_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_id      BIGINT NOT NULL REFERENCES bucket (bucket_id),
    product_id     BIGINT NOT NULL,
    quantity       INT    NOT NULL,

    CONSTRAINT uq_bucket_product
        UNIQUE (bucket_id, product_id)
);
