CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS products
(
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    price       NUMERIC(19, 2) NOT NULL,
    category_id BIGINT         NOT NULL REFERENCES categories (category_id),
    is_active   BOOLEAN        DEFAULT true
);
